spring:
  application:
    name: language-test

server:
  port: 8080



open-ai:
  chat-model:
    # langchain4j测试模型
    api-key: demo
    model-name: gpt-4o-mini
    base-url: http://langchain4j.dev/demo/openai/v1
    # 请求和响应日志
    log-requests: true
    log-responses: true

# 启用日志debug级别
logging:
  level:
    root: info
